![](../docs/banner.png)

# NumPy


## Exercises

### 1.

Import numpy under the alias `np`.

In [23]:
import numpy as np


### 2.

Create the following arrays:

1. Create an array of 5 zeros.
2. Create an array of 10 ones.
3. Create an array of 5 3.141s.
4. Create an array of the integers 1 to 20.
5. Create a 5 x 5 matrix of ones with a dtype `int`.

In [2]:
x= [0,0,0,0,0]
type(x)

list

### 3.

Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [13]:
y=np.random.rand(3,3,3)
print(y)
y.reshape(27,) 

[[[0.26469632 0.29653007 0.47922026]
  [0.04676102 0.42643872 0.73267623]
  [0.62224676 0.11403406 0.71339784]]

 [[0.75013853 0.14852992 0.50867735]
  [0.23537951 0.69868628 0.58445974]
  [0.30684928 0.14913194 0.62258689]]

 [[0.88108209 0.92330415 0.11576304]
  [0.40851252 0.97149025 0.26791774]
  [0.4123977  0.84572018 0.16996441]]]


array([0.26469632, 0.29653007, 0.47922026, 0.04676102, 0.42643872,
       0.73267623, 0.62224676, 0.11403406, 0.71339784, 0.75013853,
       0.14852992, 0.50867735, 0.23537951, 0.69868628, 0.58445974,
       0.30684928, 0.14913194, 0.62258689, 0.88108209, 0.92330415,
       0.11576304, 0.40851252, 0.97149025, 0.26791774, 0.4123977 ,
       0.84572018, 0.16996441])

### 4.

Create an array of 20 linearly spaced numbers between 1 and 10.

In [14]:
num_line = np.linspace(1,10,20)
print(num_line)


[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


### 5.

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [24]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


```python
20
```

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [30]:
a[1: , 3:]

array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

```python
array([ 6,  7,  8,  9, 10])
```

In [31]:
a[1, :]

array([ 6,  7,  8,  9, 10])

```python
array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])
```

In [33]:
a[2:4, :]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

```python
array([[ 8,  9],
       [13, 14]])
```

In [36]:
a[1:3, 2:4]

array([[ 8,  9],
       [13, 14]])

### 6.

Calculate the sum of all the numbers in `a`.

In [37]:
np.sum(a)

325

### 7.

Calculate the sum of each row in `a`.

In [39]:
row_sums = a.sum(axis=1)
print(row_sums)

[ 15  40  65  90 115]


### 8.

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [42]:
a.mean()
print(a [a>13])

[14 15 16 17 18 19 20 21 22 23 24 25]


### 9.

Find the location of the minimum value in the following array `b`:

In [49]:
np.random.seed(123)
b = np.random.randn(10)
b

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [52]:

loc_min = np.where(b == b.min())
loc_min


(array([6]),)

### 10.

Find the location of the maximum value in the following 2D array `c` (hint: there are many ways to do this question, but a quick search on stackoverflow.com will typically help you find the optimum solution for a problem, for example see [post](https://stackoverflow.com/questions/3584243/get-the-position-of-the-biggest-item-in-a-multi-dimensional-numpy-array)):

In [57]:
np.random.seed(123)
c = np.random.randn(3, 2)
c

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654]])

In [65]:

indices = np.where(c == c.max())
indices

(array([2]), array([1]))

<hr>
<hr>
<hr>